#!/bin/bash

function manage_service() {
    local action="$1"
    local service="$2"
    sudo sv "$1" "$2"
}

function fetch_output() {
    local src_dir="$1"
    echo "Performing git pull..."
    git -C "$src_dir" pull
    git -C "$src_dir" repack -a -d --depth=250 --window=250
}

function switch_config() {
    local src_dir="$1"
    ls "$src_dir" | grep -vE 'config.json' | cat -n
    read -p "Enter the number of the proxy you want to copy: " selection
    filename=$(ls "$src_dir" | grep -vE 'config.json' | sed -n "${selection}p")
    cp "${src_dir}/${filename}" "${src_dir}/config.json"
    manage_service restart xray
}

function auto_switch_config() {
    local src_dir="$1"
    local config_file="$src_dir/config.json"
    local response_check=
    local file_list=("$src_dir"/*)
    local length=${#file_list[@]}
    local indices=($(seq 0 $((length - 1)) | shuf))
    manage_service stop xraypublic
    for index in "${indices[@]}"; do
        local file="${file_list[$index]}"
        local sed_cmd_port=$(sed_cmd_port)
        sed -i "$sed_cmd_port" "$file"
        IFS=',' read -r response_check pid <<<"$(xray_connection_check "$file" false 10909)"
        if [[ "$response_check" == true ]]; then
            mv "$file" "$config_file"
            break
        fi
        kill_process "$pid" >/dev/null 2>&1
    done
    manage_service start xraypublic
}

function sed_cmd_port() {
    local sed_cmd='s#"port": 10808,#"port": 10908,#g; s#"port": 10809,#"port": 10909,#g'
    echo "$sed_cmd"
}
