#!/bin/bash

function cleanup() {
    echo "Script interrupted."
    exit 1
}

trap cleanup INT
trap '' SIGTERM

base_dir="."
workflows_dir="$base_dir/.github/workflows"
bash_dir="$base_dir/src/bash"
template_dir="$base_dir/src/template"
xray_dir="$base_dir/src/xray"
base64_dir="$base_dir/output/base64"
json_dir="$base_dir/output/json"
fragment_dir="$json_dir/fragment"
private_dir="$json_dir/private"
public_dir="$json_dir/public"
raw_dir="$json_dir/raw"
tmp_dir="$json_dir/tmp"
xray_app="$xray_dir/xray"
source "$base_dir/src/bash/base64"
source "$base_dir/src/bash/check"
source "$base_dir/src/bash/common"
source "$base_dir/src/bash/fetch"
source "$base_dir/src/bash/fragment"
source "$base_dir/src/bash/local"

function init() {
    mkdir -p "$base64_dir" "$json_dir" "$fragment_dir" "$private_dir" "$public_dir" "$raw_dir" "$tmp_dir"
}

function main() {
    init
    case "$1" in
    fetch)
        remove_items "$raw_dir" "*" "fd"
        process_configuration_urls
        remove_duplicate_file "$raw_dir"
        move_jsons_to_subdir "$raw_dir"
        generate_workflow "$raw_dir"
        ;;
    check)
        check_configs "$raw_dir/$2"
        ;;
    base64)
        remove_items "$workflows_dir" "workflow-stage-2-*.yml" "f"
        remove_items "$public_dir" "*" "fd"
        copy_items "$raw_dir" "$public_dir" ".*\[.*\] \[.*\] \[.*\]\.json$"
        copy_items "$raw_dir" "$raw_dir" "*"
        remove_items "$raw_dir" "*" "d"
        remove_items "$raw_dir" ".*\[.*\] \[.*\] \[.*\]\.json$" "f"
        remove_items "$base64_dir" "*" "f"
        base64_configs "$public_dir" "$base64_dir"
        ;;
    checkfragment)
        copy_items "$public_dir" "$fragment_dir" ".*\[.*\] \[.*-.*-ws\] \[.*\]\.json$"
        check_fragment_configs_array "$fragment_dir"
        remove_items "$fragment_dir" ".*\[.*\] \[.*\] \[.*\]\.json$" "f"
        ;;
    updatecore)
        remove_items "$xray_dir" "*" "f"
        update_core
        ;;
    localswitch)
        switch_config "$private_dir"
        ;;
    localautoswitch)
        fetch_output "$base_dir"
        copy_items "$public_dir" "$tmp_dir" "*"
        auto_switch_config "$tmp_dir"
        remove_items "$tmp_dir" ".*\[.*\] \[.*\] \[.*\]\.json$" "f"
        ;;
    gitupdate)
        git_update
        ;;
    gitreset)
        git_reset
        ;;
    *)
        exit 1
        ;;
    esac
}

main "$@"
